# -*- coding: utf-8 -*-
######################
#
# Tecnologías para la adaptación al usuario 
# en interfaces cerebro-máquina basados 
# en potenciales visuales evocados.
# 
# Aarón Pérez Martín - aapemar@gmail.com
# Universidad Autónoma de Madrid - 2019
#
# CC BY-NC-SA 4.0 License. 
# http://creativecommons.org/licenses/by-nc-sa/4.0/
#
######################

# Form implementation generated from reading ui file 'screen_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 644)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/GNB-UAM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 16, 711, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(416, 30, 91, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.spin_age = QtWidgets.QSpinBox(self.groupBox)
        self.spin_age.setGeometry(QtCore.QRect(336, 60, 42, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_age.setFont(font)
        self.spin_age.setMaximum(120)
        self.spin_age.setObjectName("spin_age")
        self.txt_session_name = QtWidgets.QLineEdit(self.groupBox)
        self.txt_session_name.setEnabled(True)
        self.txt_session_name.setGeometry(QtCore.QRect(337, 30, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_session_name.setFont(font)
        self.txt_session_name.setObjectName("txt_session_name")
        self.txt_session_cod = QtWidgets.QLineEdit(self.groupBox)
        self.txt_session_cod.setEnabled(False)
        self.txt_session_cod.setGeometry(QtCore.QRect(515, 61, 181, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_session_cod.setFont(font)
        self.txt_session_cod.setAutoFillBackground(False)
        self.txt_session_cod.setObjectName("txt_session_cod")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 61, 61, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(233, 32, 101, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.checkBox_glasses = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_glasses.setGeometry(QtCore.QRect(225, 61, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_glasses.setFont(font)
        self.checkBox_glasses.setObjectName("checkBox_glasses")
        self.txt_username = QtWidgets.QLineEdit(self.groupBox)
        self.txt_username.setGeometry(QtCore.QRect(90, 30, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_username.setFont(font)
        self.txt_username.setObjectName("txt_username")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 81, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.txt_comments = QtWidgets.QLineEdit(self.groupBox)
        self.txt_comments.setGeometry(QtCore.QRect(90, 93, 281, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_comments.setFont(font)
        self.txt_comments.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_comments.setObjectName("txt_comments")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 90, 81, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(293, 63, 41, 16))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.comboBox_gender = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_gender.setGeometry(QtCore.QRect(90, 56, 121, 32))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_gender.setFont(font)
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.session_datetime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.session_datetime.setGeometry(QtCore.QRect(514, 30, 181, 22))
        self.session_datetime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.session_datetime.setObjectName("session_datetime")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(416, 61, 91, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.btn_save_user = QtWidgets.QPushButton(self.groupBox)
        self.btn_save_user.setGeometry(QtCore.QRect(600, 90, 91, 32))
        self.btn_save_user.setObjectName("btn_save_user")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 245, 451, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(2, 34, 51, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(270, 34, 21, 16))
        self.label_9.setObjectName("label_9")
        self.spin_times_freq = QtWidgets.QSpinBox(self.groupBox_2)
        self.spin_times_freq.setGeometry(QtCore.QRect(360, 32, 42, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_times_freq.setFont(font)
        self.spin_times_freq.setMaximum(120)
        self.spin_times_freq.setObjectName("spin_times_freq")
        self.spin_freq_to = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_freq_to.setGeometry(QtCore.QRect(200, 32, 62, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_freq_to.setFont(font)
        self.spin_freq_to.setProperty("value", 0.0)
        self.spin_freq_to.setObjectName("spin_freq_to")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(316, 35, 41, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.spin_freq_from = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_freq_from.setGeometry(QtCore.QRect(63, 32, 61, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_freq_from.setFont(font)
        self.spin_freq_from.setProperty("value", 0.0)
        self.spin_freq_from.setObjectName("spin_freq_from")
        self.btn_launch_b_freq = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_launch_b_freq.setGeometry(QtCore.QRect(406, 30, 41, 32))
        self.btn_launch_b_freq.setObjectName("btn_launch_b_freq")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(170, 35, 31, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(130, 34, 21, 16))
        self.label_13.setObjectName("label_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 167, 251, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.txt_result_b_freq = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_result_b_freq.setGeometry(QtCore.QRect(15, 92, 221, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_result_b_freq.setFont(font)
        self.txt_result_b_freq.setObjectName("txt_result_b_freq")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(15, 72, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(15, 26, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.txt_result_b_elec = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_result_b_elec.setGeometry(QtCore.QRect(15, 46, 221, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_result_b_elec.setFont(font)
        self.txt_result_b_elec.setObjectName("txt_result_b_elec")
        self.btn_clear_phase = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_clear_phase.setGeometry(QtCore.QRect(140, 200, 91, 32))
        self.btn_clear_phase.setObjectName("btn_clear_phase")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(17, 157, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.txt_result_b_phase = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_result_b_phase.setGeometry(QtCore.QRect(16, 177, 221, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_result_b_phase.setFont(font)
        self.txt_result_b_phase.setObjectName("txt_result_b_phase")
        self.btn_clear_freq = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_clear_freq.setGeometry(QtCore.QRect(140, 116, 91, 32))
        self.btn_clear_freq.setObjectName("btn_clear_freq")
        self.lbl_count_b_freq = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_count_b_freq.setGeometry(QtCore.QRect(40, 120, 91, 16))
        self.lbl_count_b_freq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_count_b_freq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_count_b_freq.setObjectName("lbl_count_b_freq")
        self.lbl_count_b_phase = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_count_b_phase.setGeometry(QtCore.QRect(40, 203, 91, 16))
        self.lbl_count_b_phase.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_count_b_phase.setObjectName("lbl_count_b_phase")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 333, 451, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.spin_phase_from = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spin_phase_from.setGeometry(QtCore.QRect(170, 36, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_phase_from.setFont(font)
        self.spin_phase_from.setObjectName("spin_phase_from")
        self.spin_times_pha = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_times_pha.setGeometry(QtCore.QRect(360, 35, 42, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_times_pha.setFont(font)
        self.spin_times_pha.setMaximum(120)
        self.spin_times_pha.setObjectName("spin_times_pha")
        self.spin_phase_to = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spin_phase_to.setGeometry(QtCore.QRect(255, 36, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_phase_to.setFont(font)
        self.spin_phase_to.setObjectName("spin_phase_to")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(315, 38, 41, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.btn_launch_b_phase = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_launch_b_phase.setGeometry(QtCore.QRect(407, 31, 41, 32))
        self.btn_launch_b_phase.setObjectName("btn_launch_b_phase")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(123, 37, 41, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(226, 37, 31, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(9, 38, 41, 16))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.spin_freq = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spin_freq.setGeometry(QtCore.QRect(57, 36, 61, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_freq.setFont(font)
        self.spin_freq.setProperty("value", 0.0)
        self.spin_freq.setObjectName("spin_freq")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 430, 451, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.btn_launch_online = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_launch_online.setGeometry(QtCore.QRect(406, 30, 41, 32))
        self.btn_launch_online.setObjectName("btn_launch_online")
        self.comboBox_app = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_app.setGeometry(QtCore.QRect(90, 29, 201, 32))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_app.setFont(font)
        self.comboBox_app.setObjectName("comboBox_app")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(313, 36, 41, 16))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.spin_times_app = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_times_app.setGeometry(QtCore.QRect(360, 34, 41, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spin_times_app.setFont(font)
        self.spin_times_app.setMaximum(120)
        self.spin_times_app.setObjectName("spin_times_app")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(2, 34, 81, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(0, 79, 81, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.txt_other_electrodes = QtWidgets.QLineEdit(self.groupBox_5)
        self.txt_other_electrodes.setGeometry(QtCore.QRect(300, 79, 141, 21))
        self.txt_other_electrodes.setObjectName("txt_other_electrodes")
        self.txt_other_frequencies = QtWidgets.QLineEdit(self.groupBox_5)
        self.txt_other_frequencies.setGeometry(QtCore.QRect(300, 110, 141, 21))
        self.txt_other_frequencies.setObjectName("txt_other_frequencies")
        self.txt_other_phases = QtWidgets.QLineEdit(self.groupBox_5)
        self.txt_other_phases.setGeometry(QtCore.QRect(300, 140, 141, 21))
        self.txt_other_phases.setObjectName("txt_other_phases")
        self.groupbox_elec = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupbox_elec.setGeometry(QtCore.QRect(90, 53, 201, 51))
        self.groupbox_elec.setTitle("")
        self.groupbox_elec.setObjectName("groupbox_elec")
        self.rd_app_b_elec = QtWidgets.QRadioButton(self.groupbox_elec)
        self.rd_app_b_elec.setGeometry(QtCore.QRect(10, 24, 100, 20))
        self.rd_app_b_elec.setChecked(True)
        self.rd_app_b_elec.setObjectName("rd_app_b_elec")
        self.rd_app_other_elec = QtWidgets.QRadioButton(self.groupbox_elec)
        self.rd_app_other_elec.setGeometry(QtCore.QRect(130, 24, 61, 20))
        self.rd_app_other_elec.setChecked(False)
        self.rd_app_other_elec.setObjectName("rd_app_other_elec")
        self.groupbox_elec_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupbox_elec_2.setGeometry(QtCore.QRect(90, 85, 201, 51))
        self.groupbox_elec_2.setTitle("")
        self.groupbox_elec_2.setObjectName("groupbox_elec_2")
        self.rd_app_b_freq = QtWidgets.QRadioButton(self.groupbox_elec_2)
        self.rd_app_b_freq.setGeometry(QtCore.QRect(10, 24, 111, 20))
        self.rd_app_b_freq.setChecked(True)
        self.rd_app_b_freq.setObjectName("rd_app_b_freq")
        self.rd_app_other_freq = QtWidgets.QRadioButton(self.groupbox_elec_2)
        self.rd_app_other_freq.setGeometry(QtCore.QRect(130, 23, 61, 20))
        self.rd_app_other_freq.setChecked(False)
        self.rd_app_other_freq.setObjectName("rd_app_other_freq")
        self.groupbox_elec_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupbox_elec_3.setGeometry(QtCore.QRect(90, 117, 201, 51))
        self.groupbox_elec_3.setTitle("")
        self.groupbox_elec_3.setObjectName("groupbox_elec_3")
        self.rd_app_b_pha = QtWidgets.QRadioButton(self.groupbox_elec_3)
        self.rd_app_b_pha.setGeometry(QtCore.QRect(10, 23, 100, 20))
        self.rd_app_b_pha.setChecked(True)
        self.rd_app_b_pha.setObjectName("rd_app_b_pha")
        self.rd_app_other_pha = QtWidgets.QRadioButton(self.groupbox_elec_3)
        self.rd_app_other_pha.setGeometry(QtCore.QRect(130, 23, 61, 20))
        self.rd_app_other_pha.setChecked(False)
        self.rd_app_other_pha.setObjectName("rd_app_other_pha")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 167, 451, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 41, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(240, 31, 71, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.comboBox_elect = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_elect.setGeometry(QtCore.QRect(60, 25, 181, 32))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_elect.setFont(font)
        self.comboBox_elect.setObjectName("comboBox_elect")
        self.txt_usbport = QtWidgets.QLineEdit(self.groupBox_6)
        self.txt_usbport.setGeometry(QtCore.QRect(318, 30, 121, 21))
        self.txt_usbport.setObjectName("txt_usbport")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 410, 691, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 150, 691, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(470, 430, 251, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(15, 26, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.txt_validation_result_b_elec = QtWidgets.QLineEdit(self.groupBox_7)
        self.txt_validation_result_b_elec.setGeometry(QtCore.QRect(15, 46, 221, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_validation_result_b_elec.setFont(font)
        self.txt_validation_result_b_elec.setObjectName("txt_validation_result_b_elec")
        self.btn_clear_online = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_clear_online.setGeometry(QtCore.QRect(140, 70, 91, 32))
        self.btn_clear_online.setObjectName("btn_clear_online")
        self.lbl_validation_count_b_freq = QtWidgets.QLabel(self.groupBox_7)
        self.lbl_validation_count_b_freq.setGeometry(QtCore.QRect(40, 76, 91, 16))
        self.lbl_validation_count_b_freq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_validation_count_b_freq.setObjectName("lbl_validation_count_b_freq")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(16, 118, 121, 16))
        self.label_25.setObjectName("label_25")
        self.lbl_final_score = QtWidgets.QLabel(self.groupBox_7)
        self.lbl_final_score.setGeometry(QtCore.QRect(100, 116, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_final_score.setFont(font)
        self.lbl_final_score.setText("")
        self.lbl_final_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_final_score.setObjectName("lbl_final_score")
        self.btn_exportJSON = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_exportJSON.setGeometry(QtCore.QRect(126, 140, 121, 32))
        self.btn_exportJSON.setObjectName("btn_exportJSON")
        self.lbl_stimulus_led = QtWidgets.QLabel(self.centralwidget)
        self.lbl_stimulus_led.setEnabled(True)
        self.lbl_stimulus_led.setGeometry(QtCore.QRect(653, 9, 22, 22))
        self.lbl_stimulus_led.setText("")
        self.lbl_stimulus_led.setPixmap(QtGui.QPixmap(":/newPrefix/images/icons8-led-diode-32.png"))
        self.lbl_stimulus_led.setScaledContents(True)
        self.lbl_stimulus_led.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stimulus_led.setWordWrap(False)
        self.lbl_stimulus_led.setObjectName("lbl_stimulus_led")
        self.lbl_stimulus_monitor = QtWidgets.QLabel(self.centralwidget)
        self.lbl_stimulus_monitor.setEnabled(True)
        self.lbl_stimulus_monitor.setGeometry(QtCore.QRect(626, 11, 18, 18))
        self.lbl_stimulus_monitor.setText("")
        self.lbl_stimulus_monitor.setPixmap(QtGui.QPixmap(":/newPrefix/images/icons8-monitor-32.png"))
        self.lbl_stimulus_monitor.setScaledContents(True)
        self.lbl_stimulus_monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stimulus_monitor.setWordWrap(False)
        self.lbl_stimulus_monitor.setObjectName("lbl_stimulus_monitor")
        self.lbl_recording = QtWidgets.QLabel(self.centralwidget)
        self.lbl_recording.setEnabled(True)
        self.lbl_recording.setGeometry(QtCore.QRect(679, 4, 41, 31))
        self.lbl_recording.setText("")
        self.lbl_recording.setPixmap(QtGui.QPixmap(":/newPrefix/images/icons8-record-32.png"))
        self.lbl_recording.setScaledContents(False)
        self.lbl_recording.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recording.setWordWrap(False)
        self.lbl_recording.setObjectName("lbl_recording")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_username, self.txt_session_name)
        MainWindow.setTabOrder(self.txt_session_name, self.session_datetime)
        MainWindow.setTabOrder(self.session_datetime, self.comboBox_gender)
        MainWindow.setTabOrder(self.comboBox_gender, self.checkBox_glasses)
        MainWindow.setTabOrder(self.checkBox_glasses, self.spin_age)
        MainWindow.setTabOrder(self.spin_age, self.txt_session_cod)
        MainWindow.setTabOrder(self.txt_session_cod, self.txt_comments)
        MainWindow.setTabOrder(self.txt_comments, self.btn_save_user)
        MainWindow.setTabOrder(self.btn_save_user, self.comboBox_elect)
        MainWindow.setTabOrder(self.comboBox_elect, self.txt_usbport)
        MainWindow.setTabOrder(self.txt_usbport, self.txt_result_b_elec)
        MainWindow.setTabOrder(self.txt_result_b_elec, self.spin_freq_from)
        MainWindow.setTabOrder(self.spin_freq_from, self.spin_freq_to)
        MainWindow.setTabOrder(self.spin_freq_to, self.spin_times_freq)
        MainWindow.setTabOrder(self.spin_times_freq, self.btn_launch_b_freq)
        MainWindow.setTabOrder(self.btn_launch_b_freq, self.txt_result_b_freq)
        MainWindow.setTabOrder(self.txt_result_b_freq, self.btn_clear_freq)
        MainWindow.setTabOrder(self.btn_clear_freq, self.spin_freq)
        MainWindow.setTabOrder(self.spin_freq, self.spin_phase_from)
        MainWindow.setTabOrder(self.spin_phase_from, self.spin_phase_to)
        MainWindow.setTabOrder(self.spin_phase_to, self.spin_times_pha)
        MainWindow.setTabOrder(self.spin_times_pha, self.btn_launch_b_phase)
        MainWindow.setTabOrder(self.btn_launch_b_phase, self.txt_result_b_phase)
        MainWindow.setTabOrder(self.txt_result_b_phase, self.btn_clear_phase)
        MainWindow.setTabOrder(self.btn_clear_phase, self.comboBox_app)
        MainWindow.setTabOrder(self.comboBox_app, self.spin_times_app)
        MainWindow.setTabOrder(self.spin_times_app, self.rd_app_b_elec)
        MainWindow.setTabOrder(self.rd_app_b_elec, self.rd_app_other_elec)
        MainWindow.setTabOrder(self.rd_app_other_elec, self.txt_other_electrodes)
        MainWindow.setTabOrder(self.txt_other_electrodes, self.rd_app_b_freq)
        MainWindow.setTabOrder(self.rd_app_b_freq, self.rd_app_other_freq)
        MainWindow.setTabOrder(self.rd_app_other_freq, self.txt_other_frequencies)
        MainWindow.setTabOrder(self.txt_other_frequencies, self.rd_app_b_pha)
        MainWindow.setTabOrder(self.rd_app_b_pha, self.rd_app_other_pha)
        MainWindow.setTabOrder(self.rd_app_other_pha, self.txt_other_phases)
        MainWindow.setTabOrder(self.txt_other_phases, self.btn_launch_online)
        MainWindow.setTabOrder(self.btn_launch_online, self.btn_exportJSON)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "User and Session Information"))
        self.label_5.setText(_translate("MainWindow", "Session date:"))
        self.label_4.setText(_translate("MainWindow", "Gender:"))
        self.label.setText(_translate("MainWindow", "Session name:"))
        self.checkBox_glasses.setText(_translate("MainWindow", "Glasses"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_6.setText(_translate("MainWindow", "Comments:"))
        self.label_22.setText(_translate("MainWindow", "Age:"))
        self.session_datetime.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy HH:mm"))
        self.label_23.setText(_translate("MainWindow", "Session cod:"))
        self.btn_save_user.setText(_translate("MainWindow", "Save"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step 2: Calibration - Best Frequencies and Electrodes"))
        self.label_7.setText(_translate("MainWindow", "From:"))
        self.label_9.setText(_translate("MainWindow", "Hz"))
        self.label_18.setText(_translate("MainWindow", "Trials:"))
        self.btn_launch_b_freq.setText(_translate("MainWindow", ">"))
        self.label_8.setText(_translate("MainWindow", "To:"))
        self.label_13.setText(_translate("MainWindow", "Hz"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results"))
        self.label_10.setText(_translate("MainWindow", "Best Freq.:"))
        self.label_11.setText(_translate("MainWindow", "Best Elect.:"))
        self.btn_clear_phase.setText(_translate("MainWindow", "Clear"))
        self.label_12.setText(_translate("MainWindow", "Best Phase:"))
        self.btn_clear_freq.setText(_translate("MainWindow", "Clear"))
        self.lbl_count_b_freq.setText(_translate("MainWindow", "0 trials"))
        self.lbl_count_b_phase.setText(_translate("MainWindow", "0 trials"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Step 3: Calibration - Best Phases"))
        self.label_21.setText(_translate("MainWindow", "Trials:"))
        self.btn_launch_b_phase.setText(_translate("MainWindow", ">"))
        self.label_16.setText(_translate("MainWindow", "From:"))
        self.label_17.setText(_translate("MainWindow", "To:"))
        self.label_26.setText(_translate("MainWindow", "Freq.:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Step 4: Validation"))
        self.btn_launch_online.setText(_translate("MainWindow", ">"))
        self.label_19.setText(_translate("MainWindow", "Trials:"))
        self.label_15.setText(_translate("MainWindow", "Application:"))
        self.label_24.setText(_translate("MainWindow", "Using best:"))
        self.rd_app_b_elec.setText(_translate("MainWindow", "Electrodes"))
        self.rd_app_other_elec.setText(_translate("MainWindow", "Other"))
        self.rd_app_b_freq.setText(_translate("MainWindow", "Frequencies"))
        self.rd_app_other_freq.setText(_translate("MainWindow", "Other"))
        self.rd_app_b_pha.setText(_translate("MainWindow", "Phases"))
        self.rd_app_other_pha.setText(_translate("MainWindow", "Other"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Step 1: Configuration"))
        self.label_14.setText(_translate("MainWindow", "Map:"))
        self.label_20.setText(_translate("MainWindow", "USB port:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Results"))
        self.label_28.setText(_translate("MainWindow", "Detected Frequencies:"))
        self.btn_clear_online.setText(_translate("MainWindow", "Clear"))
        self.lbl_validation_count_b_freq.setText(_translate("MainWindow", "0 trials"))
        self.label_25.setText(_translate("MainWindow", "Final Score:"))
        self.btn_exportJSON.setText(_translate("MainWindow", "Export to JSON"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actiona.setText(_translate("MainWindow", "a"))


import resources_rc
